config/routes.rb
Rails.application.routes.draw do

devise_for :users

root 'pages#home'
get '/pages/:page' => 'pages#show'
get '/about' => 'pages#about'
get '/contact' => 'pages#contact'

get 'users/:user_id/orders' => 'users#index', as: :user_orders
get 'users/:user_id/orders/:id' => 'users#show', as: :user_order
get 'users/:user_id/orders/:id/edit' => 'users#edit', as: :edit_user_order
patch 'users/:user_id/orders/:id' => 'users#update', as: :update_user_order
delete 'users/:user_id/orders/:id' => 'users#destroy'


 resources :shops do
   get 'orders/fullfilled' => 'orders#fulfilled_orders', as: :orders_completed
     resources :orders do
        put 'completed'
        put 'estimated'
        put 'paid'
        put 'cancel'
        put 'forgotten'
        put 'reject'
        put 'accept'
      end
   end
end

app/models/shop.rb
class Shop < ActiveRecord::Base

has_many :orders, dependent: :destroy
has_many :users, :through => :orders


STATE = ['ACT','NSW','QLD','VIC','TAS','WA','NT','SA']
validates :street_num, presence: true
validates :street, presence: true
validates :suburb, presence: true
validates :state, inclusion: { in: STATE }
validates :postcode, presence: true


end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController

  before_action :set_shop, only:[:edit, :update, :show, :destroy]
  before_action :set_all_shops, except:[:new, :show, :edit]

  def index
  end

  def new
    @shop = Shop.new
  end

  def create
    @shop = Shop.create(shop_params)
    if @shop.save
      redirect_to shops_path, notice: "Shop successfully created"
    else
      render 'new'
    end
  end

  def edit
  end

  def show
  end

  def update
    if @shop.update(shop_params)
      redirect_to shops_path, notice: "Shop successfully updated"
    else
      render 'edit'
    end
  end

  def destroy
    @shop.destroy
    redirect_to shops_path, notice: "Shop successfully deleted"
  end

  private
    def shop_params
      params.require(:shop).permit(:street_num, :street, :suburb, :state, :postcode)
    end

    def set_shop
      @shop = Shop.find(params[:id])
    end

    def set_all_shops
      @shops = Shop.all
    end
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/views/shops/about.html.haml
.container
  %h1 ABOUT US PAGE
  %p some text goes here about stuff and other stuff and other stuff

app/views/shops/edit.html.haml
=simple_form_for @shop do |f|
  %h1 Edit Konoha Shop
  = f.input :street_num, placeholder: 'street number', label: false
  = f.input :street, placeholder: "street", label: false
  = f.input :suburb, placeholder: "suburb", label: false
  = f.input :state, collection: Shop::STATE, prompt: "select state", label: false
  = f.input :postcode, placeholder: "postcode", label: false
  = f.button :submit

app/views/shops/index.html.haml
.container
  %table.table.table-condensed.table-hover
    %tr
      %h2= ('Konoha Coffee Shop Location').pluralize(@shops.count)
    - @shops.each do |shop|
      %tr
        %td= "#{shop.street_num} #{shop.street}"
        %td= shop.suburb
        %td= shop.state
        %td= shop.postcode
        %td=link_to "Place Order", new_shop_order_path(shop), class: "btn btn-default"
        -if current_user_admin?
          %td
            .btn-group-vertical
              .btn.btn-default.dropdown-toggle{"data-toggle" => "dropdown", :type => "button"}
                Shop Details
                %span.caret
              %ul.dropdown-menu
                %li
                  =link_to "Current Orders", shop_orders_path(shop), class: "btn btn-default"
                %li
                  =link_to "Completed Orders", shop_path(shop), method: :get, class: "btn btn-default"
                %li
                  =link_to "Edit Shop", edit_shop_path(shop), class: "btn btn-default"

app/views/shops/new.html.haml
%h1.center.jumbotron Add Coffee Shop

%form.form-horizontal.form-group 
= simple_form_for @shop do |f|
  = f.input :name, placeholder: 'name'
  = f.input :description, cols: 40, rows: 7, placeholder: "Shop description"
  = f.button :submit 

app/views/shops/show.html.haml
.container
  %h2 Completed Orders
  %table.table.table-condensed.table-hover
    %th Name
    %th Coffee
    %th Order completed
    %th
    %th
    - @shop.orders.completed.each do |order|
      %tr
        %td= "#{order.last_name}, #{order.first_name}"
        %td= "#{order.coffee_type} / #{order.milk} / #{order.size}"
        %td= time_ago_in_words(order.completed_at) +" ago"
        %td
          =link_to "Picked up", shop_order_paid_path(@shop, order), method: :put, class: "btn btn-default"
        %td
          =link_to "Forgotten", shop_order_forgotten_path(@shop, order), method: :put, class: "btn btn-default"

  %h2 Discarded Orders
  %table.table.table-condensed.table-hover
    %th Name
    %th Coffee
    %th Order discarded
    %th State
    %th
    - @shop.orders.discarded.each do |order|
      %tr
        %td= "#{order.last_name}, #{order.first_name}"
        %td= "#{order.coffee_type} / #{order.milk} / #{order.size}"
        %td= time_ago_in_words(order.completed_at) +" ago"
        %td= order.state
        %td
          =link_to "Remove", shop_order_path(@shop, order), method: :delete, class: "btn btn-default"