config/routes.rb
Rails.application.routes.draw do

devise_for :users

root 'pages#home'
get '/pages/:page' => 'pages#show'
get '/about' => 'pages#about'
get '/contact' => 'pages#contact'

get 'users/:user_id/orders' => 'users#index', as: :user_orders
get 'users/:user_id/orders/:id' => 'users#show', as: :user_order
get 'users/:user_id/orders/:id/edit' => 'users#edit', as: :edit_user_order
patch 'users/:user_id/orders/:id' => 'users#update', as: :update_user_order
delete 'users/:user_id/orders/:id' => 'users#destroy'


 resources :shops do
   get 'orders/fullfilled' => 'orders#fulfilled_orders', as: :orders_completed
     resources :orders do
        put 'completed'
        put 'estimated'
        put 'paid'
        put 'cancel'
        put 'forgotten'
        put 'reject'
        put 'accept'
      end
   end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :orders, dependent: :destroy
  has_many :shops, :through => :orders

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true, format: /\A\S+@\S+\z/



  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
# before_filter :configure_sign_up_params, only: [:create]
# before_filter :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.for(:sign_up) << :attribute
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.for(:account_update) << :attribute
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
# before_filter :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  #  end

  # POST /resource/sign_in
  #  def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  #protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.for(:sign_in) << :attribute
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :set_user
  before_action :set_order, except: [:index]

  def index
    @orders = @user.orders
  end

  def edit
  end

  def update
    if @order.update(order_params)
      redirect_to user_orders_path(@user), notice: "Order successfully updated"
    else
      render 'edit'
    end
  end

  def destroy
    @order.destroy
    redirect_to user_orders_path(@user)
  end

private

  def set_user
    @user = User.find(params[:user_id])
  end

  def set_order
    @order = @user.orders.find(params[:id])
  end

  def order_params
    params.require(:order).permit(:first_name, :last_name, :email, :comment, :coffee_type, :milk, :size, :pickup_time)
  end

end

app/helpers/users_helper.rb
module UsersHelper

  def order_new(order)
    order.state == "new"
  end

end

app/views/users/edit.html.haml
.container
  = simple_form_for [@user, @order] do |f|
    %h1.formheading Current Order
    %p Change your order
    .form-group
    = f.input :first_name, label: false, autofocus: true, placeholder: 'name'
    = f.input :last_name, label: false, placeholder: 'last name'
    = f.input :email, label: false, placeholder: 'email'
    = f.input :coffee_type, autofocus: true, collection: Order::COFFEE_TYPE, prompt: "Select Coffee", label: false
    = f.input :milk, collection: Order::MILK, prompt: "Select Milk", label: false
    = f.input :size, collection: Order::SIZE, as: :radio_buttons, wrapper: :vertical_radio_and_checkboxes, label: false
    = f.input :pickup_time, as: :time
    = f.input :comment, placeholder: "Additional comments", label: false
    = f.submit

app/views/users/edit_order.html.haml
.container
  = simple_form_for [@user, @order] do |f|
    %h1.formheading Current Order
    %p Change your order
    .form-group
    = f.input :first_name, label: false, autofocus: true, placeholder: 'name'
    = f.input :last_name, label: false, placeholder: 'last name'
    = f.input :email, label: false, placeholder: 'email'
    = f.input :coffee_type, autofocus: true, collection: Order::COFFEE_TYPE, prompt: "Select Coffee", label: false
    = f.input :milk, collection: Order::MILK, prompt: "Select Milk", label: false
    = f.input :size, collection: Order::SIZE, as: :radio_buttons, wrapper: :vertical_radio_and_checkboxes, label: false
    = f.input :pickup_time, as: :time
    = f.input :comment, placeholder: "Additional comments", label: false
    = f.submit

app/views/users/index.html.haml
.container
  - if @user.orders.any?
    %h2= "#{@user.first_name}'s Order".pluralize(@user.orders.count)
    %table.table.table-condensed
      %th.h3 Coffee
      %th.h3 Location
      %th.h3 Status
      %th.h3 Manage Order

      - @user.orders.each do |order|
        %tr
          %td= "#{order.size} #{order.coffee_type} with #{order.milk}"
          %td= "#{order.shop.street_num} #{order.shop.street}, #{order.shop.suburb}, #{order.shop.state}"
          %td= order.state
          - if order_new(order)
            %td
              .btn-group-vertical
                .btn.btn-default.dropdown-toggle{"data-toggle" => "dropdown", :type => "button"}
                  Change / Cancel Order
                  %span.caret
                %ul.dropdown-menu
                  %li
                    =link_to "Cancel order", user_order_path(@user, order), method: :delete, class: "btn btn-default"
                  %li
                    =link_to "Change order", edit_user_order_path(@user, order), class: "btn btn-default"
          - else
            %td
              =link_to "Remove from history", user_order_path(@user, order), method: :delete, class:"btn btn-default"

  - else
    %h2= "No orders exist currently for #{@user.first_name}"