config/routes.rb
Rails.application.routes.draw do

devise_for :users

root 'pages#home'
get '/pages/:page' => 'pages#show'
get '/about' => 'pages#about'
get '/contact' => 'pages#contact'

get 'users/:user_id/orders' => 'users#index', as: :user_orders
get 'users/:user_id/orders/:id' => 'users#show', as: :user_order
get 'users/:user_id/orders/:id/edit' => 'users#edit', as: :edit_user_order
patch 'users/:user_id/orders/:id' => 'users#update', as: :update_user_order
delete 'users/:user_id/orders/:id' => 'users#destroy'


 resources :shops do
   get 'orders/fullfilled' => 'orders#fulfilled_orders', as: :orders_completed
     resources :orders do
        put 'completed'
        put 'estimated'
        put 'paid'
        put 'cancel'
        put 'forgotten'
        put 'reject'
        put 'accept'
      end
   end
end

app/models/order.rb
class Order < ActiveRecord::Base

belongs_to :shop
belongs_to :user

COFFEE_TYPE = ['Expresso', 'Cappuccino', 'Flat White', 'Latte Mocha', 'Macchiato']
MILK = ['Regular milk','Low fat milk','Soy milk','Almond milk']
SIZE = ['Large','Medium','Small']

validates :first_name, presence: true
validates :last_name, presence: true
validates :email, presence: true, format: /\A\S+@\S+\z/
validates :coffee_type, inclusion: { in: COFFEE_TYPE }
validates :milk, inclusion: { in: MILK }
validates :size, inclusion: { in: SIZE }

scope :completed, -> { where(state: 'completed') }
scope :discarded, -> { where(state: ['rejected','cancelled','forgotten']) }
scope :working, -> { where(state: 'working') }
scope :new_orders, -> { where(state: 'new') }
scope :paid, -> { where(state: 'paid') }

  def estimate!(estimate)
   update_attributes({pickup_time: estimate, state: 'working'}) #estimate_taken: Time.now, estimate_given: estimate,
 end

 def paid!
   update_attributes({finished_at: Time.now, state: 'paid'})
 end

 def complete!
   update_attributes({completed_at: Time.now, state: 'completed'})
 end

 def accept!
   update_attributes({state: 'working'})
 end

 def reject!
   update_attributes({completed_at: Time.now, state: 'rejected'})
 end

 def cancel!
   update_attributes({completed_at: Time.now, state: 'cancelled'})
 end

 def forgotten!
   update_attributes({completed_at: Time.now, state: 'forgotten'})
 end

 def modified_pickup_time
   pickup_time + estimate_given.minutes
 end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

   helper_method :sort_column, :sort_direction
   before_action :set_shop
   before_action :set_orders, except: [:index, :show, :update, :edit, :new, :create, :fulfilled_orders]

   def index
    @orders = @shop.orders.order(sort_column + " " + sort_direction)
   end

   def new
     @order = @shop.orders.new
     @order.user = current_user
   end

   def edit
     @order = @shop.orders.find(params[:id])
   end

   def update
     @order = @shop.orders.find(params[:id])
     if @order.update(order_params)
       render 'create', notice: "Order successfully updated"
     else
       render 'edit'
     end
   end

  def show
    redirect_to root_path, notice: "Orders Successfully deleted"
  end

  def create
    @order = @shop.orders.new(order_params)
    @order.user = current_user if user_signed_in?
    @order.save
    UserMailer.order_email(@order).deliver_now
   # Amount in cents
   @amount = 500

    customer = Stripe::Customer.create(
     :email => params[:stripeEmail],
     :card  => params[:stripeToken] )

    charge = Stripe::Charge.create(
     :customer    => customer.id,
     :amount      => @amount,
     :description => 'Rails Stripe customer',
     :currency    => 'usd' )

   rescue Stripe::CardError => e
     flash[:error] = e.message
     redirect_to new_shop_order_path(@shop)

  end

  def fulfilled_orders
  end

  def completed
    @order.complete!
    UserMailer.completed_email(@order).deliver_now
    redirect_to shop_orders_path(@shop), notice: "Order successfully completed"
  end


  def paid
    @order.paid!
    redirect_to shop_orders_path(@shop), notice: "Order paid for!"
  end

  def estimated
    @order.estimate!(params[:estimate])
    UserMailer.confirmation_email(@order).deliver_now
    redirect_to shop_orders_path(@shop), notice: "Order successfully delayed"
  end

  def accept
    @order.accept!
    redirect_to shop_orders_path(@shop), notice: "Order accepted"
  end

  def reject
    @order.reject!
    UserMailer.rejection_email(@order).deliver_now
    redirect_to shop_orders_path(@shop), notice: "Order rejected"
  end

  def cancel
    @order.cancel!
    redirect_to shop_orders_path(@shop), notice: "Order cancelled"
  end

  def forgotten
    @order.forgotten!
    redirect_to shop_orders_path(@shop)
  end


 private
  def order_params
    params.require(:order).permit(:first_name, :last_name, :email, :comment, :coffee_type, :milk, :size, :pickup_time)
  end

  def set_shop
    @shop = Shop.find(params[:shop_id])
  end

  def set_orders
    @order = @shop.orders.find(params[:order_id])
  end

   def order_params
    params.require(:order).permit(:first_name, :last_name, :email, :comment, :coffee_type, :milk, :size, :pickup_time)
   end

   def sort_column
    @shop.orders.column_names.include?(params[:sort]) ? params[:sort] : "last_name"
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end

end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_order_form.html.haml
.container
  = simple_form_for [@shop, @order] do |f|
    - if @order.new_record?
      %h1.formheading Coffee Orders
      %p Fill in the type of coffee you would like.
    - else
      %h1.formheading Edit Your Order
      %p Please change your order details.
    .form-group
    - if user_signed_in?
      = f.input :first_name, label: false, input_html: {:value => @order.user.first_name}
      = f.input :last_name, label: false, input_html: {:value => @order.user.last_name}
      = f.input :email, label: false, input_html: {:value => @order.user.email}
    - else
      = f.input :first_name, label: false, autofocus: true, placeholder: 'Name', required: true
      = f.input :last_name, label: false, placeholder: 'Last name'
      = f.input :email, label: false, placeholder: 'Email'
    = f.input :coffee_type, autofocus: true, collection: Order::COFFEE_TYPE, prompt: "Select coffee", label: false
    = f.input :milk, collection: Order::MILK, prompt: "Select milk", label: false
    = f.input :size, collection: Order::SIZE, as: :radio_buttons, wrapper: :vertical_radio_and_checkboxes, checked: :Large, label: false
    = f.input :pickup_time, as: :time, ampm: true, start_hour: 7, end_hour: 18, default: Time.now
    = f.input :comment, placeholder: "Additional comments", label: false
    - if @order.new_record?
      %script{src: "https://checkout.stripe.com/checkout.js", class: "stripe-button", "data-image" => image_path("coffee.png"), "data-key" => Rails.configuration.stripe[:publishable_key], "data-description" => "Coffee Payment $5.00", "data-amount" => "500", "data-locale" => "auto"}
    - else
      = f.submit

app/views/orders/create.html.haml
%form
  %h1= "Thank you, #{@order.first_name}"

  %p Your order is being processed.
  %br
  %p= "#{@order.size} #{@order.coffee_type} with #{@order.milk}"

  %br
  %p= "You will receive an email at #{@order.email} once your order is confirmed"
  %br
  %p
    =link_to "Place another order", shops_path, method: :get, class: "btn btn-default"
    =link_to "Change order", edit_shop_order_path(@shop, @order), class: "btn btn-default"
    =link_to "Cancel order", shop_order_cancel_path(@shop, @order), class: "btn btn-default"
    =link_to "Home", shops_path, class: "btn btn-default"

app/views/orders/edit.html.haml
= render 'order_form'

app/views/orders/index.html.haml
.container
  - if @orders.working.any?
    %h2= ('Working Order').pluralize(@orders.working.count)
    %table.table.table-condensed.table-hover
      %th.col-md-1= sortable 'Name'
      %th.col-md-3 Coffee Type
      %th.col-md-1 Placed @
      %th.col-md-1 Pickup @
      %th.col-md-2= sortable 'pickup_time' , 'Time remaining'
      %th.col-md-2 Mark as completed
      %th.col-md-2 Cancel order
      - @orders.working.each do |order|
        %tr
          %td= "#{order.last_name},  #{order.first_name}"
          %td= "#{order.coffee_type} / #{order.milk} / #{order.size}"
          %td= order.created_at.strftime("%-I:%M %P")
          %td= order.pickup_time.strftime("%-I:%M %P")
          - if order.pickup_time > Time.now
            %td= distance_of_time_in_words(order.pickup_time, Time.now)
          - else
            %td.text-danger= time_ago_in_words(order.pickup_time) +' overdue'
          %td
            =link_to "Completed", shop_order_completed_path(@shop, order), method: :put, class: "btn btn-default"
          %td
            =link_to "Cancel", shop_order_cancel_path(@shop, order), method: :put , class: "btn btn-default"
  - else
    %h2 No current orders in progress

  - if @orders.new_orders.any?
    %h2= ('New Order').pluralize(@orders.new_orders.count)
    %table.table.table-condensed.table-hover
      %th.col-md-1= sortable "Name"
      %th.col-md-3 Coffee Type
      %th.col-md-1 Placed @
      %th.col-md-1 Pickup @
      %th.col-md-2 Time Remaining
      %th.col-md-2 Accept/Delay Order
      %th.col-md-2 Reject Order
      - @orders.new_orders.each do |order|
        %tr
          %td= "#{order.last_name},  #{order.first_name}"
          %td= "#{order.coffee_type} / #{order.milk} / #{order.size}"
          %td= order.created_at.strftime("%-I:%M %P")
          %td= order.pickup_time.strftime("%-I:%M %P")
          %td= distance_of_time_in_words(order.pickup_time, Time.now)
          %td
            .btn-group-vertical
              .btn.btn-default.dropdown-toggle{"data-toggle" => "dropdown", :type => "button"}
                Accept/Delay
                %span.caret
              %ul.dropdown-menu
                %li
                  =link_to "Accept", shop_order_accept_path(@shop, order), method: :put, class: "btn btn-default dropdown-toggle"
                %li
                  =link_to "+5 min", shop_order_estimated_path(@shop, order, estimate: order.pickup_time + 5.minutes), method: :put, class: "btn btn-default dropdown-toggle"
                %li
                  =link_to "+10 min", shop_order_estimated_path(@shop, order, estimate: order.pickup_time + 10.minutes), method: :put, class: "btn btn-default dropdown-toggle"
                %li
                  =link_to "+15 min", shop_order_estimated_path(@shop, order, estimate: order.pickup_time + 15.minutes), method: :put, class: "btn btn-default dropdown-toggle"
          %td
            =link_to "Reject", shop_order_reject_path(@shop, order), method: :put, class: "btn btn-default"
          %td
  - else
    %h2 No new orders awaiting action

app/views/orders/new.html.haml
= render 'order_form'