config/routes.rb
Rails.application.routes.draw do

devise_for :users

root 'pages#home'
get '/pages/:page' => 'pages#show'
get '/about' => 'pages#about'
get '/contact' => 'pages#contact'

get 'users/:user_id/orders' => 'users#index', as: :user_orders
get 'users/:user_id/orders/:id' => 'users#show', as: :user_order
get 'users/:user_id/orders/:id/edit' => 'users#edit', as: :edit_user_order
patch 'users/:user_id/orders/:id' => 'users#update', as: :update_user_order
delete 'users/:user_id/orders/:id' => 'users#destroy'


 resources :shops do
   get 'orders/fullfilled' => 'orders#fulfilled_orders', as: :orders_completed
     resources :orders do
        put 'completed'
        put 'estimated'
        put 'paid'
        put 'cancel'
        put 'forgotten'
        put 'reject'
        put 'accept'
      end
   end
end

app/views/layouts/_footer.html.haml
%div.footer.navbar-static-bottom.navbar-inverse
  %div.container
    %div.row
      %div.col-md-2.col-md-offset-2
        %h3 Who We Are
        %p=link_to 'More about us', '#'

      %div.col-md-2.col-md-offset-1
        %h3 Links
        %ul.list-unstyled
          %li=link_to 'Great Coffee', '#'
          %li=link_to 'Roast your own', '#'

      %div.col-md-2.col-md-offset-1
        %h3 Stay in Touch
        %ul.list-unstyled
          %li=link_to 'Facebook', '#'
          %li=link_to 'Twitter', '#'

app/views/layouts/_header.html.haml
.navbar.navbar-static-top.navbar-inverse{:role => "navigation"}
  .container-fluid
    .navbar-header
      %button.navbar-toggle{"data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      .navbar-brand Konoha Coffee
    #bs-example-navbar-collapse-1.collapse.navbar-collapse
      %ul.nav.navbar-nav.navbar-right
        %li
          %a.center=link_to "Home", root_path
        %li
          %a=link_to "About Us", about_path
        %li
          %a=link_to "Contact Us", contact_path
        - if user_signed_in?
          %li
            %a=link_to 'Edit Account', edit_user_registration_path
          %li
            %a=link_to 'View Orders', user_orders_path(current_user)
          %li
            %a=link_to 'Sign Out', destroy_user_session_path, method: :delete
        - else
          %li
            %a=link_to "Sign Up", new_user_registration_path
          %li
            %a=link_to "Log In", new_user_session_path

app/views/layouts/_messages.html.haml
- flash.each do |key, value|
 %div{:class => "alert alert-#{key}"}
  = value

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Order Online
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body.Site
    = render 'layouts/header'
    %main.Site-content
      - if notice
        = render 'layouts/messages'
      = yield
    = render 'layouts/footer'